# Generated by Django 5.0.4 on 2024-05-06 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hw5_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderProduct",
        ),
    ]
