# Generated by Django 5.0.4 on 2024-05-06 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hw5_app", "0002_rename_orderitem_orderproduct"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderProduct",
            new_name="OrderItem",
        ),
    ]
