# Generated by Django 5.0.4 on 2024-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hw5_app", "0003_rename_orderproduct_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Общая сумма заказа",
            ),
        ),
    ]
